### ISSUE TITLE
Chat - Uncaught

### ISSUE THREAD

**Issue by isabel42** [42-Student-Teams/ft_transcendence#12]
Message entre deux utilisateurs cela donne cette erreur. 
Soit les utilisateurs bloqués ou pas. 

<img width="720" alt="Screenshot 2024-08-28 at 16 54 11" src="https://github.com/user-attachments/assets/02caf4d0-6a4c-4b3b-a926-97526683a63c">

**Comment by jwikiera** [comment]
on it

**Comment by jwikiera** [comment]
Fixed
